In [18]:
import numpy as np

In [19]:
irises = np.load('irises.npy')
print(irises.shape)

(120, 4)


In [20]:
types = np.load('types.npy')
print(types.shape)

(120,)


In [21]:
new_irises = np.load('new_irises.npy')
print(new_irises.shape)

(30, 4)


In [22]:
n, m = len(irises), len(new_irises)
print("Number of training samples (n):", n)
print("Number of test samples (m):", m)

Number of training samples (n): 120
Number of test samples (m): 30


In [23]:
def calc_two_loops(new_points, points):
    
    #‌ m is the number of new points (test samples)
    m = len(new_points)
    # n is the number of points (training samples)
    n = len(points)
    # Distance matrix
    d = np.zeros((m, n))
    
    # For each new point
    for i in range(m):
        # For each point
        for j in range(n):
            # Calculate the distance between the two points
            d[i, j] = np.sum(np.square(new_points[i] - points[j]))
            
    return d

In [24]:
d2 = calc_two_loops(new_irises, irises)
print(d2.shape)

(30, 120)


In [25]:
def calc_one_loop(new_points, points):
    
    #‌ m is the number of new points (test samples)
    m = len(new_points)
    # n is the number of points (training samples)
    n = len(points)
    # Distance matrix
    d = np.zeros((m, n))
    
    # For each new point
    for i in range(m):
        # Calculate the distance between the new point and all the points
        d[i] = np.sum(np.square(np.subtract(new_points[i], points)), axis = 1)  
    return d

In [26]:
d1 = calc_one_loop(new_irises, irises)
print(d1.shape)

(30, 120)


In [27]:
def calc_no_loop(new_points, points):
    return np.sum(np.square(np.subtract(new_points.reshape(30, 1, 4), points.reshape(1, 120, 4))), axis = 2)

In [28]:
d = calc_no_loop(new_irises, irises)
print(d.shape)

(30, 120)


In [29]:
if np.allclose(d, d1, 1e-5) and np.allclose(d, d2, 1e-5) and np.allclose(d1, d2, 1e-5):
    print('Fine!')
else:
    print('There is something wrong!')

Fine!


In [30]:
k = 10
k_nearest = np.argpartition(d, k - 1, axis = 1)
k_nearest = k_nearest[::, 0:10:]
print(k_nearest)

[[  6  14   0  32  22  17  23  37  39  21]
 [ 10   1  30  24  20   2  36   3   6  28]
 [ 27  13   8  39   4  29  15  12  26  25]
 [ 14  17   0  39  37  22   8  32  26  13]
 [ 21  20  30   3   9  24   6  19  35   5]
 [  3   9  24  38   2  36   5  30  10   1]
 [ 10   1  30  24  20   2  36   3   6  28]
 [  0   6  22  23  21  14   9  32  17  39]
 [ 39  35  17  22   4  21  37  19   8  16]
 [ 28   6  23   0  14  21  30  32  22   9]
 [ 47  73  69  61  52  51  41  60 101  58]
 [ 71  43  65  64  77  74  72  66  76  54]
 [ 71  65  74  64  66  77  76  54  57  49]
 [ 64  65  74  66  43  50  54  72  77  71]
 [ 78  60  47  41  73  52  63  57  51  59]
 [ 74  65  54  64  66  43  50  57  71  75]
 [ 77  71  44  53  72  76  49  63  56  97]
 [ 72  66  64  74  43  65  77  54  71  76]
 [ 77  74  44  72  71  76  54  66  43  53]
 [ 66  54  71  76  77  74  49  57  44  72]
 [ 90 103 106  96 112 115  93  83  80 110]
 [ 82  96 100 108  94 115 112 105  80  84]
 [111  92  97 117  81 114 102  91 101  56]
 [107  67  

In [31]:
k_nearest_types = types[k_nearest]
k_nearest_types

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [2, 1, 2, 2, 1, 2, 2, 2, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2,

In [32]:
from scipy import stats
predicted_types = stats.mode(k_nearest_types, axis=1, keepdims=False).mode.reshape(m)
predicted_types

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [33]:
new_types = np.load('new_types.npy')
accuracy = np.sum(np.equal(new_types, predicted_types)) / len(predicted_types)
print('Accuracy:', accuracy)

Accuracy: 1.0
